apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluence
  name: confluence
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
      name: confluence
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: sinchrony
  selector:
    app: confluence
