apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence
  labels:
    app: confluence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
    spec:
      containers:
        - image: us.gcr.io/juanluis-personal/confluence
          name: confluence
          ports:
            - containerPort: 8090
              name: confluence
            - containerPort: 8091
              name: synchrony
          volumeMounts:
            - name: confluence-persistent-storage
              mountPath: /var/atlassian/application-data/confluence
      volumes:
        - name: confluence-persistent-storage
          persistentVolumeClaim:
            claimName: confluence-volumeclaim
