apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluence
  name: confluence
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    app: confluence
